---
image: registry.gitlab.com/aplus-framework/images/builder

cache:
  paths:
    - vendor/
    - node_modules/

test:sass:
  image: node:10.19
  stage: test
  before_script:
    - npm install -g sass
  script:
    - mkdir -p build/assets/css/
    - sass --trace assets/css/main.scss:build/assets/css/main.css
  artifacts:
    paths:
      - build/

test:jekyll:
  image: ruby:2.7
  stage: test
  script:
    - bundle install --path vendor
    - bundle exec jekyll build -d build/
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  dependencies:
    - test:sass
    - test:jekyll
  script:
    - mkdir public/
    - mv build/* public/
  artifacts:
    paths:
      - public/
  only:
    - master
