---
image: registry.gitlab.com/aplus-framework/images/builder

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: guide, tests, vendor

test:php:
  stage: test
  cache:
    paths:
      - build/
      - vendor/
  before_script:
    - composer install
  script:
    - composer normalize --dry-run --indent-size=4 --indent-style=space
    - php sass-compiler.php
    - php views-builder.php
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  dependencies:
    - test:build
  environment:
    name: production
    url: https://aplus-framework.gitlab.io
  script:
    - mv build/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
