---
cache:
  paths:
    - vendor/
    - node_modules/

test:sass:
  image: node:10.15
  stage: test
  before_script:
    - npm install -g sass
  script:
    - mkdir -p build/assets/css/
    - sass --trace assets/css/main.scss:build/assets/css/main.css
  artifacts:
    paths:
      - build

test:jekyll:
  image: ruby:2.5
  stage: test
  dependencies:
    - test:sass
  script:
    - bundle install --path vendor
    - bundle exec jekyll build -d build/
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - test:jekyll
  script:
    - mkdir public/
    - mv build/* public/
  artifacts:
    paths:
      - public
  only:
    - master
