---
image: ruby:2.5

cache:
  paths:
    - vendor/

before_script:
  - gem install sass
  - bundle install --path vendor

test:build:
  stage: test
  script:
    - bundle exec jekyll build -d build/
    - sass --trace assets/css/main.scss:build/assets/css/main.css
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies:
    - test:build
  script:
    - mkdir public/
    - mv build/* public/
  artifacts:
    paths:
      - public
  only:
    - master
