---
url: http://localhost:4000
title: Front
timezone: America/Sao_Paulo

markdown: kramdown
highlighter: false
kramdown:
  syntax_highlighter_opts:
    disable: true
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - jekyll-serve
  - sass-watch
  - README.md
