---
url: https://the-framework.gitlab.io/front
title: Front
timezone: America/Sao_Paulo

markdown: kramdown
highlighter: false
kramdown:
  syntax_highlighter_opts:
    disable: true
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
